---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  roles:
   - role: tests/test_port
     vars:
       port: "5044"       
  tasks:

  - name: check logstash port result 
    assert:
        that:
           - "{{ output_port.failed }} == false"    
  



