---
# tasks file for test_port
  - name: test elasticsearch data link
    shell: curl -X GET "http://localhost:{{ port }}/_cat/indices/my-index-*?v=true&s=index&pretty"
    args:
     executable: /bin/bash
    register: output_elasticsearch_cat_indicies
