---
- name: reload systemd configuration
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
    - molecule_yml is not defined 
  register: es_restarted

- name: restart elasticsearch  CentOS7 MOLECULE
  service: name=elasticsearch state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
    - molecule_yml is defined and ansible_os_family == 'RedHat'
  register: es_restarted


- name: restart elasticsearch Ubuntu MOLECULE
  shell: >
    skill -u elasticsearch && \
    chown  -R elasticsearch:elasticsearch /var/run/elasticsearch/ && \
    chmod -R 0750 /var/run/elasticsearch/ && \
    sudo -u elasticsearch /usr/share/elasticsearch/bin/systemd-entrypoint -p /var/run/elasticsearch/elasticsearch.pid -quiet &
  when:
    - es_restart_on_change
    - es_start_service
    - molecule_yml is defined and ansible_os_family == 'Debian'
  register: es_restarted
