---
- name: Install elasticsearch for tests MOLECULE
  include_role:
    name: elasticsearch
  when:
    - molecule_yml is defined


- set_fact: "kb_major_version={{ kibana_version.split('.')[0] }}.x"
  when:
      - kb_major_version is undefined
  tags:
      - always

- name: Set repo name variable.
  set_fact:
    kb_repo_name: "{{ kb_major_version }}"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana Debian.
  apt:
    name: '{{ kibana_package }}{% if kibana_version is defined and kibana_version != ""  %}={{ kibana_version }}{% endif %}'
    state: "{{ kibana_package_state }}"
  when:
    - ansible_os_family  == "Debian"

- name: Install Kibana RedHat.
  yum:
    name: '{{ kibana_package }}{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %}'
    state: "{{ kibana_package_state }}"
  when:
    - ansible_os_family  == "RedHat"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana